PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?gene ?geneLabel ?PMCID ?quote WHERE {
  wd:#SRNA_QID# p:#REG_PROPERTY# ?statement.
  ?statement ps:#REG_PROPERTY# ?gene.
  ?statement prov:wasDerivedFrom ?refnode.
  ?refnode pr:P932 ?PMCID.
  ?refnode pr:P1683 ?quote.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}